#!/bin/bash
echo -e "\nInstalling tar\n"
sudo apt install tar -y
echo -e "\nDownloading HiddifyCli from Github\n"
wget https://github.com/hiddify/hiddify-core/releases/download/v3.1.8/hiddify-cli-linux-amd64.tar.gz
echo -e "\nExtracting from tar.gz\n"
tar -xvzf hiddify-cli-linux-amd64.tar.gz
rm hiddify-cli-linux-amd64.tar.gz
echo -e "\nMoving HiddifyCli to /usr/bin\n"
sudo mv HiddifyCli /usr/bin/
chmod +x /usr/bin/HiddifyCli
touch server.txt
echo "sudo HiddifyCli run -c ./server.txt -d ./config.json" > bash_start
echo -e "\nDone\n\n"
sleep 2
echo -e "Now put your vless or vmess server link into server.txt and run bash_start using bash\n"
echo -e "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"
sleep 6
