#!/bin/bash


showHelp(){
echo "Help:"
echo "remove            removes the docker"
}


installDocker(){
echo ""
echo "Installing docker for debian ..."
echo ""
sleep 2

sudo apt-get update
echo ""
sleep 0.2
sudo apt-get install ca-certificates curl
sleep 0.2
sudo install -m 0755 -d /etc/apt/keyrings
sleep 0.2
sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
sleep 0.2
sudo chmod a+r /etc/apt/keyrings/docker.asc
sleep 0.2

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

echo ""
sleep 0.2
sudo apt-get update
echo ""
sleep 0.2
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
echo ""
echo ""
sleep 0.2
docker --version
sleep 3
echo ""

while true; do
echo ""
echo -n "do you want to run hello-world container? (y/n) "
read answer
echo ""
    if [[ "$answer" == "y" || "$answer" == "Y" ]]; then
        echo "Sure, running docker command..."
        echo ""
        sudo docker run hello-world
        break
    elif [[ "$answer" == "n" || "$answer" == "N" ]]; then
        echo "Sure, good luck then ;)"
        echo ""
        break
    else
        echo ""
        echo "invalid input entered, please try again..."
    fi
done
}

remove_docker(){
echo ""
echo "removing docker initialized ..."
echo ""
sleep 2
sudo apt autoremove -y docker-ce docker-ce-cli
echo ""
echo ""
if dpkg -l | grep -q "^ii  docker-ce"; then
        echo "removing encountered problems !!!"
        sleep 2
    else
        echo "docker removed successfully."
        sleep 2
fi
}




if [ "$#" -lt 1 ]; then
    if dpkg -l | grep -q "^ii  docker-ce"; then
        echo "docker-ce is already installed."
    else
        installDocker
    fi
else
    for arg in "$@"; do
        if [[ "$arg" == "remove" ]]; then
            remove_docker
        elif [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
            showHelp
        else
            echo "enter -h or --help for help menu."
        fi
    done
fi
