#!/bin/bash
echo ""
echo "Installing docker for debian ..."
echo ""
sleep 2

sudo apt-get update
echo ""
sleep 1
sudo apt-get install ca-certificates curl
echo ""
sleep 1
sudo install -m 0755 -d /etc/apt/keyrings
echo ""
sleep 1
sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
echo ""
sleep 1
sudo chmod a+r /etc/apt/keyrings/docker.asc
echo ""
sleep 1

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

echo ""
sleep 1
sudo apt-get update
echo ""
sleep 1
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
echo ""
sleep 1
docker --version
echo ""
