#!/bin/bash

opkg update

opkg list-upgradable | cut -f 1 -d ' ' | xargs -r opkg upgrade

opkg remove dnsmasq

opkg install dnsmasq-full

opkg install kmod-nft-tproxy kmod-nft-socket

wget -O passwall.pub https://master.dl.sourceforge.net/project/openwrt-passwall-build/passwall.pub

opkg-key add passwall.pub
rm passwall.pub

echo "read release arch << EOF" > tmp
echo "\$(. /etc/openwrt_release ; echo \${DISTRIB_RELEASE%.*} \$DISTRIB_ARCH)" >> tmp
echo "EOF" >> tmp
echo "" >> tmp
echo "for feed in passwall_packages passwall2; do" >> tmp
echo " echo \"src/gz \$feed https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-\$release/\$arch/\$feed\" >> /etc/opkg/customfeeds.conf" >> tmp
echo "done" >> tmp

bash tmp
rm tmp

opkg update

opkg install luci-app-passwall2
#opkg install v2ray-geosite-ir

echo ""
echo "Done"
echo ""
sleep 5

uci del passwall2.myshunt.DirectGame
uci del passwall2.DirectGame
uci del passwall2.myshunt.ProxyGame
uci del passwall2.ProxyGame
uci del passwall2.myshunt.Direct
uci del passwall2.Direct
uci del passwall2.myshunt.GooglePlay
uci del passwall2.GooglePlay
uci del passwall2.Netflix
uci del passwall2.OpenAI
uci del passwall2.myshunt.Proxy
uci del passwall2.Proxy
uci del passwall2.myshunt.China
uci del passwall2.China
uci del passwall2.myshunt.QUIC
uci del passwall2.QUIC
uci del passwall2.UDP

reboot
