image = "bento/ubuntu-24.04"

Vagrant.configure("2") do |config|

  config.vm.box = image

   config.vm.provider "virtualbox" do |vb|

     #vb.gui = true
     vb.name = "test-vm"
     vb.memory = "1024"
     vb.cpus = 1

   end

   config.vm.provision "shell", path: "bootstrap.sh"

end
