#!/bin/bash

#version
minikube_version='v1.33.1'
kubectl_version='v1.33.1'

minikube(){
curl -LO https://github.com/kubernetes/minikube/releases/$minikube_version/download/minikube-linux-amd64
sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
minikube start
}

kubectl(){
curl -LO https://dl.k8s.io/release/$kubectl_version/bin/linux/amd64/kubectl
curl -LO "https://dl.k8s.io/release/$kubectl_version/bin/linux/amd64/kubectl.sha256"
echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
if (( $? == 0 )); then
  sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  kubectl version --client
else
  echo "file validation went wrong"
fi
}

minikube
kubectl
